### ISSUE TITLE
Add Documentation for userdata.sh around MOUNT_POINT

### ISSUE THREAD

**Issue by campbel** [ahromis/ddc-terraform#1]
Hi,

Been looking at the scripts which have been helpful for my setup. I noticed there was a lock of comments / documentation around the mounting. I was curious what this was being used for. Might be helpful to add some documentation in the README or a comment above the section below.

`````` MOUNT_POINT=/var/lib/docker
mkdir -p ${MOUNT_POINT}
mkfs -t ext4 /dev/xvdb
mount /dev/xvdb ${MOUNT_POINT}
echo "/dev/xvdb ${MOUNT_POINT} ext4 defaults,nofail 0 2" >> /etc/fstab```

Thanks
``````

**Comment by ahromis** [comment]
Hi @campbel. Thanks for pointing that out, I should probably spend some time updating the readme.

Regarding your question, this is essentially mounting `/var/lib/docker` as it's own volume. So when the instances come up the EBS volume will be mounted as `/var/lib/docker` and the machine will be ready for a Docker install. It's best practice (depending on your storage driver) to mount `/var/lib/docker` as a separate filesystem. This prevents containers/images from filling up the root filesystem and causing issues on the host.

That userdata script is mounting this 20GB EBS volume as the Docker volume when the instance is created.

https://github.com/ahromis/ddc-terraform/blob/master/hosts.tf#L26-L32

**Comment by campbel** [comment]
@ahromis thanks for the quick reply! I'll have to incorporate this practice into my setup as well. Thank you.
